# Generated by Django 5.2.4 on 2025-07-23 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etk_retriever", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrieverequests",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retrieverequests",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CaptchaSolving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.TextField()),
                ("solved_text", models.TextField()),
                ("is_solved", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="etk_retriever.credentials",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondFactorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("second_factor", models.TextField()),
                ("is_captured", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="etk_retriever.credentials",
                    ),
                ),
            ],
        ),
    ]
